zuul:
   prefix: /api
   routes:
      demo-server:
         path: /server/**
         serviceId: demo-server
      demo-client:
         path: /client/**
         serviceId: demo-client


eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
         instance:
            hostname: localhost
            
spring:
   application:
      name: zuul-service
      
server:
   port: 8079
   

hysterix:
   command:
      default:
         execution:
            isolation:
               thread:
                  timeoutInMilliseconds:60000                    